
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TextAnalysisTools
{
    /// <summary>
    /// Mutually execulsive Type of token generated by Tokenizer
    /// </summary>
    public enum TokenType
    {
        Article,
        Chapitre,
        Number,
        String,
        Operator,
        Delimiter,
        Comment,
        Alena,
        Paragraph,
        Section,
        Titre,
        test,
        AlenaS,

        Keyword,
        Builtins,

        WhiteSpace,
        Identifier,

        Unknown
    }
}
