
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Lexer
{
    /// <summary>
    /// Mutually execulsive Type of token generated by Tokenizer
    /// </summary>
    public enum TokenType
    {
        Article,
        Chapitre,
        Number,
        String,
        Operator,
        Delimiter,

        Keyword,
        Builtins,

        WhiteSpace,
        Identifier,

        Unknown
    }
}
